version: "3.9"

services:
  frontend:
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: "true"
      WATCHPACK_POLLING: "true"
    ports:
      - "5173:5173"

  backend:
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"